substitutions:
  # _PROJECT_ID: actemo-demo
  _REGION: asia-northeast1
  _SERVICE_NAME: actemo-server

steps:  
### 1. Build the Docker image
  - id: "build image"
    name: "gcr.io/kaniko-project/executor:latest"
    args: 
      - --destination=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=168h
      - --dockerfile=SER_model/Dockerfile.prod

## 2. Deploy
  - id: "deploy prod service"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["run", "deploy", "${_SERVICE_NAME}", "--image", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA", "--port", "8080", "--region", "${_REGION}"]

options:
  logging: CLOUD_LOGGING_ONLY 

