# 1. 도커 이미지 빌드
# docker build -f Dockerfile.dev -t actemo:dev .
# 2. 도커 컨테이너 실행
# docker run -it --rm --name actemo-dev -p 8000:8000 -v $(pwd):/root/code actemo:dev /bin/bash

# Specifies base image and tag
FROM python:3.8-slim-buster as base
WORKDIR /root

# Update the package lists and install sudo
RUN apt-get update && apt-get install -y sudo ffmpeg && rm -rf /var/lib/apt/lists/*
# Install ffmpeg
FROM base as builder
COPY requirements.txt .
RUN pip install --user --progress-bar=on -r requirements.txt

FROM base as final
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
WORKDIR /root/code
# ENTRYPOINT ["python", "train.py"]

