# 1. 도커 이미지 빌드
# docker build -f Dockerfile.dev -t actemo:dev .
# 2. 도커 컨테이너 실행
# docker run -it --rm --name actemo-dev -v $(pwd):/root/code actemo:dev /bin/bash

# Specifies base image and tag
FROM pytorch/pytorch:latest
WORKDIR /root

# Installs additional packages
RUN pip install numpy pandas librosa tqdm torchaudio 

# Downloads training data
# RUN curl https://example-url/path-to-data/data-filename --output /root/data-filename

# Sets up the entry point to invoke the trainer.
WORKDIR /root/code
# ENTRYPOINT ["python", "train.py"]

